# Generated by Django 5.0.1 on 2024-04-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_time_alter_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
