# Generated by Django 5.0.1 on 2024-04-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_message_date_alter_message_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='time',
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
